### ISSUE TITLE
How to create thumbnails from DICOM files and convert them to JPEG or PNG

### ISSUE THREAD

**Issue by bartekupartek** [Enet4/dicom-rs#109]
Hello, I'm researching if would it be possible to parse DICOM files, extract pixel data and resize it as thumbnail in  i.e. JPEG, so it would be possible to preview in any web browser, if it's possible how could I approach it by dicom-rs?

**Comment by Enet4** [comment]
Hello, @bartekupartek. This is related to #63 and #31. Currently, pixel data manipulation has to be done manually, by retrieving the necessary attributes and interpreting those as a complete image.

A better abstraction for looking at objects as images is planned, and is in my priority list after lazy loading (#1).

**Comment by Enet4** [comment]
The new pixeldata API should now enable you to obtain an image value out of a DICOM object. Creating a thumbnail would amount to resizing the image afterwards. You may keep track of development around this crate in #125.

**Comment by waleed51** [comment]
hi, sorry for that but I didn't understand how to convert .dcm files to jpg/png images, 
please if there is any solution provided kindly help me? 

i use these dicom images with angular app (typescript)

**Comment by Enet4** [comment]
Hello @waleed51! Nowadays the DICOM-rs project encompasses a CLI tool which does just that! See [`dicom-toimage`](https://crates.io/crates/dicom-toimage) to convert a DICOM file to an image file (you can also see how this is done in its [source code](https://github.com/Enet4/dicom-rs/tree/master/toimage)).

I also made a small proof-of-concept DICOM image viewer [here](https://github.com/Enet4/simple-dicom-viewer).

**Comment by desprit** [comment]
@Enet4 
Quick question. 
I tested `dicom-toimage` and it worked perfectly for the most of my images. Since it's a CLI tool and I needed to execute directly from the wasm code I then tried to use `decode_pixel_data` functionality from another package to extract pixel data from my images to then use as thumbnails. I think I misunderstood the logic behind it but I though that `dicom-toimage` and `pixel_data` share the core functions. However extraction of pixel data isn't working for me due to it being `1.2.840.10008.1.2.4.70 (JPEG Lossless, Non-Hierarchical, First-Order Prediction)` syntax #125. Could you please shed some light on it, what would be the most straightforward way today to create a thumbnail of a dicom file (in a web app)?

**Comment by Enet4** [comment]
@desprit `dicom-toimage` already uses `dicom-pixeldata` underneath to decode the pixel data and interpret it as an image. The code in `dicom-toimage` is also a great example on how to use the API for this purpose.

JPEG Lossless is already supported, thanks to `jpeg-decoder` supporting the lossless mode of operation in the standard. The only thing that you need to do is ensure that the Cargo feature `jpeg` in `dicom-transfer-syntax-registry` is enabled, which is already enabled by default when importing `dicom-pixeldata`.

If necessary, feel free to reach out on [Zulip](https://dicom-rs.zulipchat.com) with the code that you are trying.

**Comment by desprit** [comment]
@Enet4 Thanks for always being so helpful! By adding `dicom-transfer-syntax-registry` I was able to extract pixels.
