### ISSUE TITLE
How to work with SQ tags

### ISSUE THREAD

**Issue by iberisoft** [Enet4/dicom-rs#117]
Sorry for this stupid question but I tried to do my best for a few hours... better to ask here. Perhaps, this is a problem of my bad skills with Rust.

I have a `DicomValue<I, P>` object with SQ tags. I call `items` to further iterating thru `[I]` However, `I` is a simple `EmptyObject` structure by default so I have no idea how to retrieve the sequence items.

Can you share a sample code of working with SQ tags?

**Comment by Enet4** [comment]
Hello! Here is a quick example based on some code from the `dcmdump` crate:

```rust
let file = open_file("path/to/file.dcm")?;
let other_patient_ids = file.element(Tag(0x0010, 0x1002))?;
match other_patient_ids.value() {
    DicomValue::Sequence { items, .. } => {
        for item in items {
            // each item should be an object of its own
            let patient_id = item.element(Tag(0x0010, 0x0020))?;
            println!("Also known as: {}", patient_id.to_string());
        }
    }
    _other => {
        // not a sequence, bad DICOM object
    }
}
```

> However, `I` is a simple `EmptyObject` structure by default so I have no idea how to retrieve the sequence items.

Note that when I = [`EmptyObject`](https://docs.rs/dicom-core/0.4.0/dicom_core/header/enum.EmptyObject.html), this usually means that the value is sure to not have any items. Perhaps the object was constructed in such a way that it assumed to never have any nested data sets? In that case, the code might need some minor changes in the element construction calls so that it assumes the object to containing elements of type `InMemElement`, and so be a DICOM object of type `InMemDicomObject`.

If necessary, please provide a minimal reproducible example so that the problem can be diagnosed.
