### ISSUE TITLE
[object] Skip reading pixel data for fast parsing

### ISSUE THREAD

**Issue by bastien-solutions** [Enet4/dicom-rs#134]
Hello, 

This is a question, is it possible to read only meta-data part of (large) files (without pixel data) to optimize processing time ?

**Comment by Enet4** [comment]
Hello! The short answer is not yet, but that is indeed planned and an implementation should arrive soon-ish. This is being tracked in #1.

**Comment by bastien-solutions** [comment]
See that, but I expect there are an option in `dicom_object::open_file` in the meantime.
Anyway thank you for your fast response and you fabulous work.
Did you have an idea about release time of lazy loading feature?

**Comment by Enet4** [comment]
> See that, but I expect there are an option in `dicom_object::open_file` in the meantime.

I suppose that an additional function which loads a DICOM object in-memory without any pixel data could be added as a quick 
 workaround, and it should be easy to implement. I admit that the pixel data can be ignored entirely in some use cases. Pull requests are welcome, and I can provide additional guidance if necessary.

#1 would be more generic so that it can serve other use cases, such as reading image frames independently, or for not loading certain heavier data sequences when not necessary. Committing to a deadline has been a bit difficult, as it depends a lot on how much of my free time is invested on this, but I've been wanting to bring this to the library for quite a while. I will try to pick this up this weekend.
