### ISSUE TITLE
Writing DICOM files?

### ISSUE THREAD

**Issue by pauldotknopf** [Enet4/dicom-rs#15]
I've been working on SCU/SCP support. I've had to pause because of the missing write support.

With that said, what are you thinking with regards to writing? Do you want to stub out some traits and then I will handle the implementation/tests?

**Comment by pauldotknopf** [comment]
I'm thinking that lazy loading should be implemented first.

The reason being, I think lazy loaded values shouldn't be loaded into memory when writing the dataset to another writer. I fear that if we don't consider this when stubbing, it will be difficult to change afterwards.

**Comment by Enet4** [comment]
The current status of this issue is that this feature is under active development. Hopefully, the first design should facilitate lazy loading in the future:

1. (**ongoing**) Objects implement a way to turn its data elements into data _tokens_, a representation which is also used by the decoding process.
2. (**done**) A sequence of data tokens can be unambiguously written to a byte writer in a way that is DICOM compliant.
3. (**todo**) A function to save objects to a file would combine the first two capabilities in order to know to write the preamble, followed by the file meta group and the rest of the data tokens, by turning these into tokens and writing them sequentially.

The implementation of (1) is particularly tricky because DICOM objects yield multiple data tokens per elements, sometimes in a recursive fashion (sequences), Rust still does not have a stable syntax for generators yet, and `impl Traits` cannot be matched with associated types. Hopefully some of these pieces can be reused in different DICOM object implementations, so that a lazy DICOM object can be made without a full rewrite.

I'm afraid I cannot establish a deadline for this, but this is definitely something that an MVP would have. Reading and writing DICOM data is a key feature set. There will be a major pull request from me once it's done.
