### ISSUE TITLE
Trailing NULLs should be trimmed from UIs

### ISSUE THREAD

**Issue by troelsarvin** [Enet4/dicom-rs#166]
I'm working with a set of million of DICOM files where I need to extract study instance UID from the fil and use the SIUID as strings  for subsequent work. For a surpringly large set of files, my subsequent use of the SIUID has been failing. It turns out the failing SIUIDs all have trailing NULL bytes. It's a nasty issue to debug, because when you print strings with NULL bytes to the console, you may not see the NULL bytes.

The DICOM standard has an (odd) requirment to pad unique identifiers (UIs) with NULLs, if they don't have an even length. As a natural consequence of this, I believe it's generally expected, that DICOM libraries trim trailing NULLs when returning UIs to applications.

I suggest dicom-rs trim trailing null bytes when returning UIs such as when using dicom_object::element_by_name("StudyInstanceUID").

**Comment by Enet4** [comment]
It is true that trailing whitespaces are a common trend when working with DICOM data. The way that this is handled in the DICOM-rs library is to provide utility methods. This is already possible in v0.4, the code below should be enough for your use case:

```rust
use dicom::object::open_file;
use dicom::dictionary_std::tags;

let obj = open_file("CT0001.dcm")?
let stuid = obj.element(tags::STUDY_INSTANCE_UID)?.to_clean_str()?;
```

This could probably be handled in a different way, although I find the current approach reasonable: all values are fetched as they are, and cleaning them up is an explicit, easily available operation.

**Comment by troelsarvin** [comment]
I believe the need to run to_clean_str() breaks the principle of least surprise: One wouldn't expect to have to deal with DICOM protocol details like padding when asking for the study instance UID, for example.
And I assert that other tools and libraries don't require you to handle trailing null chars when asking for UIs, but I cannot prove that assertion right now.

Also, I like the principleof the typical use being the simple use. If someone _really_ want to peek into the raw bytes of an UI, then that should be done with a special function.

**Comment by troelsarvin** [comment]
I found out about dcmtk: In dcmtk,  one doesn't need to trim trailing null-chars when getting UIs.

**Comment by michaelonken** [comment]
This is correct, and such a null char is added automatically when writing (if otherwise odd length UID), i.e. the user does not have to add it when inserting it into Study Instance UID (for example). 

I think there is no good reason why the user wants to know that there was a null byte in the end (or padding spaces for text VRs), unless you debug problems. For the latter case there should be low level methods or call parameters to hand over the padding to the user.

**Comment by Enet4** [comment]
After some thinking, I propose the following new behaviour for `PrimitiveValue` (and subsequently to `DicomValue`):

- `to_str`, `to_multi_str`, and `to_string` (`Display`) will automatically trim all whitespace and null characters at the end of textual values
- `to_clean_str` is deprecated, with the implementation changed to just call `to_str`
- A new method `to_raw_str` will do the current behaviour of `to_str`, which is not to trim any characters
- The implementation of `PartialEq` for textual values needs to be adjusted so that the values are compared in their trimmed form: `"Doe^John" == "Doe^John "` and `"1.2.3" == "1.2.3\0"`
- We will keep the current behaviour for non-textual values for the time being, but this can be revisited if a related incident is reported. 

A pull request fulfilling these criteria will be welcomed. Feel free to reach out for guidance if necessary.
