### ISSUE TITLE
Not working with python 3.8

### ISSUE THREAD

**Issue by masterwongjkd** [Enet4/dicom-rs#26]
This does not work with python 3.8. When do you think this will support that version?

**Comment by Enet4** [comment]
I'm sorry, I do not understand this issue. Were you attempting to use this Rust library from Python somehow? Perhaps you meant a different DICOM library?

**Comment by masterwongjkd** [comment]
Well, I have tried from different ways, but I am always getting this error:
![image](https://user-images.githubusercontent.com/58639311/71478385-3e0a1c00-27e7-11ea-9e88-173d758e666d.png)
What do you suggest?

**Comment by Enet4** [comment]
That error appeared because there is no such pip package named "dicom-rs", which is correct. Note that this is an implementation of the standard in pure Rust, meaning that the main API is designed for software also written in Rust. Bindings for Python would be possible, but I believe it is still too early for the project to accommodate APIs for other languages.

Closing the issue, as this appears to be just a misunderstanding. In order to use the DICOM-rs library, you would need to [learn Rust](https://rust-lang.org/learn). Otherwise, you may consider looking for a Python library instead (maybe [pydicom](https://pydicom.github.io/)).
