### ISSUE TITLE
RLE Support

### ISSUE THREAD

**Issue by chafey** [Enet4/dicom-rs#47]
Hi - I just implemented a DICOM RLE decoder in Rust which you can find here: https://github.com/chafey/dicomrle-rs

I wanted to let you know in case you want to use it for adding support for RLE decoding to this library.  I would also appreciate any feedback as I am new to Rust.  Thanks!

**Comment by Enet4** [comment]
Nice project, thank you for sharing!

While it is not quite the time to think about a possible integration (it would be best to establish an image abstraction API first), one thing to keep an eye on is whether you can take advantage of the `dicom-core` and `dicom-encoding` crates for common DICOM structures and algorithms, rather than making them from scratch. In the event that something does not fit or is missing, then that could become a source of discussion and mutual improvement.

**Comment by chafey** [comment]
I don't see anything in dicom-core or dicom-encoding that will help with the DICOM RLE Decoder.  The DICOM RLE algorithm is quite simple and self contained, it doesn't have any dependencies on anything else in DICOM.  I'll go ahead and close this issue for now as there doesn't seem to be interest in integrating.
