### ISSUE TITLE
Possible to do a minor version release 0.7.1?

### ISSUE THREAD

**Issue by chrisbll971** [Enet4/dicom-rs#550]
Hello,

I was wondering if it might be possible to do a minor version release with the latest code as 0.7.1? There are a couple features we wanted to leverage, but our company only supports mirroring the latest version on crates.io

Thanks

**Comment by PRadeckiDH** [comment]
+1 but it would be great if the JPEG-LS support PR could be merged in before a minor release :)

**Comment by Enet4** [comment]
Thank you for bringing this up. Yes, there is a need for version 0.7.1 so that the multiple patches and tweaks available may enter the crates registry. I might leave substantial features such as JPEG-LS support to a separate release (0.7.2), though this alone is not an indication of the time that it would take to bring it forward.

**Comment by chrisbll971** [comment]
That would be amazing. Thanks so much. Our project has a deadline to be released to production by 8/23

**Comment by Enet4** [comment]
:rocket: https://github.com/Enet4/dicom-rs/releases/tag/v0.7.1

> Our project has a deadline to be released to production by 8/23

Version 0.7.1 is now released, but I would like to emphasize that I cannot guarantee any strict deadlines for when a new version comes out or when certain contributions are brought upstream. Should you be interested in sponsoring the project and obtaining some form of SLA in the process, feel free to reach out by email or Zulip.

**Comment by chrisbll971** [comment]
Thank you very much and completely understand. Really appreciate it
